In [1]:
#------------------------------------------
# install pandas
#------------------------------------------
# pip install pandas
# sudo apt-get install python-pandas
# conda instal pandas

#------------------------------------------
# import section
#------------------------------------------
import pandas as pd
import numpy as np
# from pandas import *
#=========================================================
#  Pandas Datastructure | Series
#=========================================================

In [2]:
#------------------------------------------
# 1. declaring a series
#-------------------------------------------

# here default index = 0 ,1,2 ...

_series = pd.Series([1,4,-7,22,34,67,53])
_series
# series = pd.Series(np.array([1,4,-7,22,34,67,53]))   # define by np.array

0     1
1     4
2    -7
3    22
4    34
5    67
6    53
dtype: int64

In [3]:
# explicity index
_series = pd.Series([1,4,-7,22,34,67,53],index=['a','b','c','d','e','f','g'])
_series

a     1
b     4
c    -7
d    22
e    34
f    67
g    53
dtype: int64

In [4]:
# indexes and values
_series.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [5]:
_series.values

array([ 1,  4, -7, 22, 34, 67, 53], dtype=int64)

In [6]:
#------------------------------------------
# 2. Selecting the internal elements
#-------------------------------------------
# by index
_series['c']

-7

In [7]:
# by key 
_series[2]

-7

In [8]:
# multiple elements as in numpy  | by key range
_series[1:4]

b     4
c    -7
d    22
dtype: int64

In [9]:
# multiple elements | by index list
_series[['b','d']]

b     4
d    22
dtype: int64

In [10]:
#------------------------------------------
# 3. Assigning values to the elements
#-------------------------------------------
# by key
_series[2] = -222
_series

a      1
b      4
c   -222
d     22
e     34
f     67
g     53
dtype: int64

In [11]:
# by index
_series['f'] = 234345
_series

a         1
b         4
c      -222
d        22
e        34
f    234345
g        53
dtype: int64

In [12]:
#------------------------------------------
# 4. Filtering values
#-------------------------------------------
_series[_series > 100]


f    234345
dtype: int64

In [13]:
#_series[_series == 4 ] # 
_series[_series != 4 ] # not equal 4

a         1
c      -222
d        22
e        34
f    234345
g        53
dtype: int64

In [14]:
#------------------------------------------
# 5. Operations
#-------------------------------------------
# +,-,* % , / 
_series + 100  # add 100 to each element

a       101
b       104
c      -122
d       122
e       134
f    234445
g       153
dtype: int64

In [15]:
# module of 2
_series % 2  # odd(1) or even(0) 

a    1
b    0
c    0
d    0
e    0
f    1
g    1
dtype: int64

In [16]:
# log of all elements 
np.log(_series)
# np.sin , 

C:\Users\binayk\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


a     0.000000
b     1.386294
c          NaN
d     3.091042
e     3.526361
f    12.364550
g     3.970292
dtype: float64

In [17]:
np.sin(_series)   # sin,exp

a    0.841471
b   -0.756802
c   -0.868951
d   -0.008851
e    0.529083
f    0.861186
g    0.395925
dtype: float64

In [18]:
# uniqe elements
s1 = pd.Series([1,22,22,44,55,7,44,np.NaN])   # NaN : Not a NUmber   1/0
s1.unique() # uniq elements in  

array([ 1., 22., 44., 55.,  7., nan])

In [19]:
# check if certain element(s) is present or not
s1.isin([1,7])

0     True
1    False
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [20]:
s1.isin([1,7]).values

array([ True, False, False, False, False,  True, False, False])

In [21]:
s1.isin([1,7]).value_counts()

False    6
True     2
dtype: int64

In [22]:
# check if any NUll number is present
s1.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [23]:
s1.notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
dtype: bool

In [24]:
# get the Null and Not Null COunts series
s1.notnull().value_counts()

# s1.notnull().value_counts()[True]
# s1.notnull().value_counts()[False]

True     7
False    1
dtype: int64

In [25]:
# filter all not NULL elements
s1[s1.notnull()]

0     1.0
1    22.0
2    22.0
3    44.0
4    55.0
5     7.0
6    44.0
dtype: float64

In [26]:
# filter all NaN 
# s1.isnull().value_counts()[True]   # count
s1[s1.isnull()]

7   NaN
dtype: float64

In [27]:
#------------------------------------------
# 6. Series as Dictionaries
#-------------------------------------------
mydict = {'red': 20, 'blue': 10, 'yellow': 50,'orange': 70}
mydict

{'red': 20, 'blue': 10, 'yellow': 50, 'orange': 70}

In [28]:
myseries = pd.Series(mydict)
myseries

red       20
blue      10
yellow    50
orange    70
dtype: int64

In [29]:
#------------------------------------------
# 7. Operation betweeb Series
#-------------------------------------------
s1 = pd.Series([11,22,33,44,55],index=['a','b','c','d','e'])
s1

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [30]:
s2 = pd.Series({'a':111,'bb':222,'c':333})
s2

a     111
bb    222
c     333
dtype: int64

In [31]:
s1 + s2

a     122.0
b       NaN
bb      NaN
c     366.0
d       NaN
e       NaN
dtype: float64

In [32]:
# thank you 
# stay tuned for upcoming topics