In [1]:
import numpy as np

In [2]:
#-----------------------------
# create a 1D array
#----------------------------
# ndarray
_array = np.array([10,20,30,40])
_array

array([10, 20, 30, 40])

In [3]:
type(_array)

numpy.ndarray

In [4]:
# dtype   : int32,int64  : depending up the oS and python distribution
_array.dtype     

dtype('int32')

In [5]:
# dimension of array
_array.ndim

1

In [6]:
# size of array
_array.size

4

In [7]:
# shape
_array.shape

(4,)

In [8]:
#-----------------------------
# create a 2D array
#----------------------------
_array2d = np.array([[10,20,30,40],[2,3,4,5]])
_array2d

array([[10, 20, 30, 40],
       [ 2,  3,  4,  5]])

In [9]:
# dimension as 2
_array2d.ndim

2

In [10]:
# shape   | 2 row and 4 columns
_array2d.shape

(2, 4)

In [11]:
# size should return 8 = 2 x 4 
_array2d.size

8

In [12]:
# create 2d  3 x 3  array with all 0 
array0 = np.zeros((3,3))
array0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# create 2d  4 x 4  array with all 1 
array1 = np.ones((4,4))
array1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# create array from 10 to 20 
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
# create array of all EVEN numbers from 10 to 20 
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [16]:
# convert 1d array (of 0-15 ) into 2d array of 3x5
_array1 = np.arange(0,15)  
print(_array1)
_array12 = _array1.reshape(3,5)
print(_array12)

# in one line 
np.arange(0,15).reshape(3,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
#  linspace  |   splits the range into N number of interval
print(np.linspace(0,9,4) )   # N = 4
print(np.linspace(0,9,6) )   # N = 6

[0. 3. 6. 9.]
[0.  1.8 3.6 5.4 7.2 9. ]


In [18]:
# random 
print(np.random.random(5))

print(np.random.random((3,3)))

[0.65798688 0.09966224 0.22215614 0.11298507 0.92034188]
[[0.79947017 0.23849043 0.20420974]
 [0.54368015 0.18364265 0.48946312]
 [0.66174749 0.28077704 0.92156197]]


In [19]:
# ==============================
# arithmetic operators
# ==============================
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [20]:
a1  + 5    # add 5 to each element

array([5, 6, 7, 8, 9])

In [21]:
# get 10 random numbers in between 1 - 50
np.random.random(10) * 50

array([48.87178288, 32.58410373, 36.0822653 , 49.06416215, 14.86291519,
       49.67017923, 44.04337984, 36.75259118, 37.12231936, 49.83352046])

In [22]:
a1 = np.arange(21) / 2
a1

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [23]:
#==============================
# Matric Product
# ==============================
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3)) * 3
print("A:",A)
print("B:",B)

A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
B: [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [24]:
A * B   # element wise multiplication  | NOTE : not matrix multiplication 

array([[ 0.,  3.,  6.],
       [ 9., 12., 15.],
       [18., 21., 24.]])

In [25]:
np.dot(A,B)   # matrix multilication or DOT product      # there is no A . B   as . is not a arithmatic operator

array([[ 9.,  9.,  9.],
       [36., 36., 36.],
       [63., 63., 63.]])

In [26]:
#==============================
# Aggregate functions 
#  a. sum 
#  b. min 
#  c. max 
#  d. mean
#  e. standard deviation
# ==============================

arr = np.array([11,22,3,55,34,23,20])
arr

array([11, 22,  3, 55, 34, 23, 20])

In [27]:
#  a. sum 
arr.sum()

168

In [28]:
#  b. min 
arr.min()

3

In [29]:
#  c. max
arr.max()

55

In [30]:
arr.mean()

24.0

In [31]:
arr.std()

15.547163269043189

In [32]:
#==============================
# Indexing and slicing 
# ==============================

a = np.arange(10, 19)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [33]:
# 4th index | 5 the element as index starts from 0  
a[4]

14

In [34]:
# last element of array
a[-1]


18

In [35]:
# 3 rd element from last
a[-3]

16

In [36]:
# splice |  2 to 5 th index
a[2:5]

array([12, 13, 14])

In [37]:
a[1:6:2]     # 1 to 6 th index 2 : alterate


array([11, 13, 15])

In [38]:
a[:6:2]    # start index 0 


array([10, 12, 14])

In [39]:
a[::2]    # same as a[0:9:2]

array([10, 12, 14, 16, 18])

In [40]:
a[::]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [41]:
# end 